### ISSUE TITLE
Invariant Violation: requireNativeComponent: "ARTShape" was not found in the UIManager.

### ISSUE THREAD

**Issue by dentep** [tokkozhin/react-native-neomorph-shadows#51]
Running both on react-native-cli and Expo (I know you mentioned expo deprecation), I receive the following error:

```
Invariant Violation: requireNativeComponent: "ARTShape" was not found in the UIManager.

This error is located at:
    in ARTShape (at Shape.js:61)
    in Shape (at InnerShadowART.js:44)
    in ARTGroup (at Group.js:35)
    in Group (at InnerShadowART.js:43)
    in ARTSurfaceView (at Surface.js:37)
    in Surface (at InnerShadowART.js:42)
    in InnerShadowART (at Neomorph.js:150)
    in RCTView (at View.js:34)
    in View (at Neomorph.js:148)
    in RCTView (at View.js:34)
    in View (at Neomorph.js:141)
    in Neomorph (at App.js:10)
    in RCTView (at View.js:34)
    in View (at App.js:8)
    in App (created by ExpoRoot)
    in ExpoRoot (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in DevAppContainer (at AppContainer.js:121)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
at [native code]:null in flushedQueue
at [native code]:null in invokeCallbackAndReturnFlushedQueue
```

Using the example that you have provided I was unable to run any shadow effect on my app. React native v: >0.60
Adding pod manually doesn't work either. What should we do?

**Comment by EmmanuelPerezP** [comment]
Did you tried uninstalling and reinstalling your app?

**Comment by huperniketes** [comment]
This occurs because @react-native-community/art is an upgrade of an old RN package that's manually linked. Remove the manual link with

```npx react-native unlink @react-native-community/art```

and the autolinking process in RN 60+ will work correctly the next time you run

```cd ios && pod install && cd ..```.
